name: Deploy

on:
  push:
    branches: [ main, fdoxyz/gh-pages-deploy-automation ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: |
          git config --global user.email "codeland@codenewbie.org"
          git config --global user.name "GitHub Action"
          bundle exec rake publish
